name: 'DEV-CI'

on:
  push:
    branches:
    - develop
  pull_request:


jobs:

  main:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run generate --if-exists


    - name: Test
      run: echo test...



    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: |
        terraform apply -auto-approve \
          -var access_key=${{ secrets.AWS_ACCESS_KEY_ID }}
          -var secret_key=${{ secrets.AWS_SECRET_KEY }}
          -var region=${{ secrets.AWS_REGION }}


    - name: Upload to S3
      if: github.event_name == 'push'
      run: |
        aws s3 sync ./dist/ ${{ secrets.S3_BUCKET_WEBSITE }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
